apiVersion: skaffold/v2beta22
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: ghcr.io/keptn-contrib/helm-service
      docker:
        dockerfile: Dockerfile
        target: production
# Before executing this, install helm-service manually:
# helm install helm-service https://github.com/keptn/keptn/releases/download/0.8.4/helm-service-0.8.4.tgz -n keptn
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values"]
    releases:
      - name: helm-service # needs to be the same name as currently used (check via helm ls -n keptn)
        namespace: keptn # needs to be the same namespace as where the helm-chart is currently deployed
        # upgradeOnChange: true
        # recreatePods: false # don't recreate all pods
        artifactOverrides:
          image: ghcr.io/keptn-contrib/helm-service
        imageStrategy:
          helm: { }
        overrides:
          resources:
            limits:
              memory: 1024Mi
        chartPath: chart
